# Generated by Django 3.2 on 2021-07-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filesUpload',
            fields=[
                ('num_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Not Provided', max_length=50)),
                ('team', models.CharField(default='Not Provided', max_length=20)),
                ('extra', models.CharField(default='Not Provided', max_length=300)),
                ('topic', models.CharField(default='Not Provided', max_length=300)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='workFrom',
            fields=[
                ('num_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('team', models.CharField(default='', max_length=50)),
                ('ToWork', models.CharField(default='', max_length=50)),
                ('Link', models.CharField(default='', max_length=50)),
                ('lastDate', models.CharField(default='', max_length=50)),
                ('extra', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
